# -----------------------------
# USERS MUTATIONS
# -----------------------------

mutation CreateAdmin($uid: String!, $displayname: String!, $email: String!)
  @auth(level: USER) {
  user_insert(data: {userId: $uid, displayname: $displayname, email: $email, type: "admin" })
}

mutation CreateUser($uid: String!, $displayname: String!, $email: String!)
  @auth(level: USER) {
  user_insert(data: {userId: $uid, displayname: $displayname, email: $email, type: "client"})
}

mutation UpdateUser($userId: String!, $displayname: String, $email: String)
  @auth(level: USER) {
  user_update(key: {userId: $userId}, data: {displayname: $displayname, email: $email})
}

mutation DeleteUser($userId: String!)
  @auth(level: USER) {
  user_delete(key: {userId: $userId})
}

# -----------------------------
# PLACES MUTATIONS
# -----------------------------

mutation CreatePlace($name: String!, $description: String, $coordinates: String!, $images: [String!])
  @auth(level: USER) {
  place_insert(data: {name: $name, description: $description, coordinates: $coordinates, images: $images})
}

mutation UpdatePlace($placeId: UUID!, $name: String, $description: String, $coordinates: String, $images: [String!])
  @auth(level: USER) {
  place_update(key: {placeId: $placeId}, data: {name: $name, description: $description, coordinates: $coordinates, images: $images})
}

mutation DeletePlace($placeId: UUID!)
  @auth(level: USER) {
  place_delete(key: {placeId: $placeId})
}

# -----------------------------
# ROUTES MUTATIONS
# -----------------------------

mutation CreateRoute($userId: String!, $name: String!, $description: String)
  @auth(level: USER) {
  route_insert(data: {userId: $userId, name: $name, description: $description})
}

mutation UpdateUserAvatar($userId: String!, $avatarKey: String!)
  @auth(level: USER) {
  user_update(
    key: { userId: $userId },
    data: { 
      avatarKey: $avatarKey
    }
  )
}
