# -----------------------------
# USERS QUERIES
# -----------------------------

query ListUsers @auth(level: USER) {
  users {
    userId
    displayname
    email
    createdAt
  }
}

query GetUser($userId: String!) @auth(level: USER) {
  user(key: { userId: $userId }) {
    userId
    displayname
    email
    createdAt
    type
    avatarKey
  }
}

query IsAdmin($userId: String!) @auth(level: USER) {
  user(key: { userId: $userId }) {
    type
  }
}

query GetUserByEmail($email: String!) @auth(level: USER) {
  users(where: {email: {eq: $email}}) {
    userId
    email
    displayname
    createdAt
    avatarKey
    type
  }
}

query GetUserByDisplayname($displayname: String!) @auth(level: USER) {
  users(where: {displayname: {eq: $displayname}}) {
    userId
    email
    displayname
    createdAt
  }
}

# -----------------------------
# PLACES QUERIES
# -----------------------------

query ListPlaces @auth(level: USER) {
  places {
    placeId
    name
    description
    coordinates
    images
    createdAt
  }
}

query GetPlace($placeId: UUID!) @auth(level: USER) {
  place(key: { placeId: $placeId }) {
    placeId
    name
    description
    coordinates
    images
    createdAt
  }
}

# -----------------------------
# ROUTES QUERIES
# -----------------------------

query ListRoutes @auth(level: USER) {
  routes {
    routeId
    name
    description
    userId
    createdAt
  }
}

query GetRoute($routeId: UUID!) @auth(level: USER) {
  route(key: { routeId: $routeId }) {
    routeId
    name
    description
    userId
    createdAt
  }
}

# Get User Avatar Key
query GetUserAvatarKey($userId: String!) @auth(level: USER) {
  user(key: { userId: $userId }) {
    avatarKey
  }
}
